name: node-ci

on: [push]

env:
  CI: true

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: npm install and lint
        run: |
          npm install
          npm run lint

      - name: Test (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd ..
          cd D:\a\react-shader-canvas\react-shader-canvas
          npm test

      - name: Test (Unix)
        if: matrix.os != 'windows-latest'
        run: npm test
